version: '3.7'

services:
  user-domain:
    build:
      target: $TARGET
    environment:
      PYTHON_ENV: $PYTHON_ENV
      PORT: $PORT
      PG_USER: $PG_USER
      PG_DATABASE: $PG_DATABASE
      PG_PASSWORD: $PG_PASSWORD
      PG_HOST: $PG_HOST
    volumes:
      - ./src:/app/src
    ports:
      - $PORT:$PORT

networks:
  default:
    external:
      name: development
