version: '3.7'
services:
  postgres:
    container_name: postgres
    build:
      context: .
    restart: always
    environment:
      PG_USER: $PG_USER
      PG_DATABASE: $PG_DATABASE
      PG_PASSWORD: $PG_PASSWORD
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
    driver: local

networks:
  default:
    external:
      name: development